# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool: 'Default'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    packageApp: true
    archivePath: 'output/$(SDK)/$(Configuration)'
    signingOption: 'default'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11 Pro Max'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output/$(SDK)/$(Configuration)'
    ArtifactName: 'Dicee Artifacts'
    publishLocation: 'Container'