# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool: 'Default'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphonesimulator'
    packageApp: true
    archivePath: '/Users/anrigiorganashvili/Desktop/DevOps/Azure_Agent/Artifacts'
    signingOption: 'default'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11 Pro Max,OS=13.6'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls /Users/anrigiorganashvili/Desktop/DevOps/Azure_Agent/Artifact
      
      # zip x.zip /Users/anrigiorganashvili/Library/Developer/Xcode/DerivedData/BMB-iOS-*/Build/Products/Debug-iphonesimulator/BMB-Debug.app

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/Users/anrigiorganashvili/Desktop/DevOps/Azure_Agent/Artifact'
    ArtifactName: 'Dicee Artifacts'
    publishLocation: 'Container'